export const BUSINESS_END_POINT = "/business";
export const BUSINESS_ID_END_POINT = "/:business_id";
export const BUSINESS_UPDATE_END_POINT = "/:business_id";
export const ALL_BUSINESS_END_POINT = "/All";
export const CREATE_BUSINESS_END_POINT = "/register";
export const CREATE_BUSINESS_PROJECT_END_POINT = "project/:business_id/project";
export const GET_ALL_BUSINESS_PROJECT_END_POINT = "project/all_project";
export const DELETE_BUSINESS_PROJECT_END_POINT = "project/:project_id";
export const UPDATE_EMAIL_AND_PHONE = "/email_and_phone/:business_id";
export const GET_PROJECT_BY_EMAIL = "/project/:email";
export const GET_PROJECT_BY_ID="/project/business/:project_id"
