export const CHECKOUT_SESSION_ENDPOINT = 'v1/checkout-session';

export enum EntityPlan {
  MULTI_VENUE_SAME_LOCATION_PLAN = 'MULTI_VENUE_SAME_LOCATION_PLAN',
  MULTI_VENUE_MULTI_BRANCH_PLAN = 'MULTI_VENUE_MULTI_BRANCH_PLAN',
  HOTEL_PLAN = 'HOTEL_PLAN',
  INDIVIDUAL_VENUE_PLAN = 'INDIVIDUAL_VENUE_PLAN',
  KIDS_SPACE_SAME_LOCATION_PLAN = 'KIDS_SPACE_SAME_LOCATION_PLAN',
  KIDS_SPACE_MULTI_BRANCH_PLAN = 'KIDS_SPACE_MULTI_BRANCH_PLAN',
}

export const CHECKOUT_SESSION_SUCCESS_URL = 'https://dev.findmyvenue.com/payment-success-confirmation';

export enum EntityType {
  'MULTI_VENUE' = 'MULTI_VENUE',
  'HOTEL' = 'HOTEL',
  'INDIVIDUAL_VENUE' = 'INDIVIDUAL_VENUE',
}
