export const CONFIG_ENDPOINT = '/v1/config';

export const SECTION = {
  AMENITIES: 'AMENITIES',
  OVERVIEW: 'OVERVIEW',
  FACILITIES_AND_EQUIPMENTS : 'FACILITIES_AND_EQUIPMENTS'

};

export enum Section {
  AMENITIES = 'AMENITIES',
  OVERVIEW = 'OVERVIEW',
  FACILITIES_AND_EQUIPMENTS = 'FACILITIES_AND_EQUIPMENTS'
}

export enum DBkeys {
  'HOTEL#OVERVIEW#BASIC#HOTEL_TYPE',
  'HOTEL#OVERVIEW#BASIC#HOTEL_VIEW',
  'HOTEL#OVERVIEW#BASIC#HOTEL_STYLE',
  'HOTEL#OVERVIEW#ADDITIONAL#EVENT_TYPE',
}
