export enum EventCategory {
  BUSINESS = 'BUSINESS',
  WEDDING_AND_DINING = 'WEDDING_AND_DINING',
  PARTIES = 'PARTIES',
  ART_AND_CULTURAL = 'ART_AND_CULTURAL',
  KIDS = 'KIDS',
}

export const EventCategoryMapping = ["BUSINESS","WEDDING_AND_DINING","PARTIES","ART_AND_CULTURAL","KIDS"]


export enum EventSubcategory {
  CONFERENCE_SEMINAR = 'CONFERENCE_SEMINAR',
  CORPORATE_EVENTS = 'CORPORATE_EVENTS',

  WEDDINGS = 'WEDDINGS',
  DINING = 'DINING',
  BANQUET = 'BANQUET',

  SOCIAL_PARTIES = 'SOCIAL_PARTIES',
  CLUBBING_NIGHT_OUT = 'CLUBBING_NIGHT_OUT',
  DRINKS_RECEPTIONS = 'DRINKS_RECEPTIONS',
  CHRISTMAS_PARTIES = 'CHRISTMAS_PARTIES',
  BABY_SHOWER_TEA_PARTY = 'BABY_SHOWER_TEA_PARTY',
  CHILDREN_TEEN = 'CHILDREN_TEEN',
  GENERIC_TAGS = 'GENERIC_TAGS',

  FILMING_PHOTOGRAPHY = 'FILMING_PHOTOGRAPHY',
  CULTURAL = 'CULTURAL',
  ART_SPACES = 'ART_SPACES',
  PERFORMANCES_EXHIBITIONS = 'PERFORMANCES_EXHIBITIONS',
  NONE = 'NONE',
}

export const VenueEventCategorySubcategoryMapping = {
  BUSINESS : ["CONFERENCE_SEMINAR","CORPORATE_EVENTS"],
  WEDDING_AND_DINING : ["WEDDINGS","DINING","BANQUET"],
  PARTIES : ["SOCIAL_PARTIES","CLUBBING_NIGHT_OUT","DRINKS_RECEPTIONS","CHRISTMAS_PARTIES","BABY_SHOWER_TEA_PARTY","CHILDREN_TEEN","GENERIC_TAGS"],
  ART_AND_CULTURAL : ["FILMING_PHOTOGRAPHY","CULTURAL","ART_SPACES","PERFORMANCES_EXHIBITIONS"],
  KIDS : null
}