export const PLAN_ENDPOINT = '/v1/plans';
export const GET_PRICE_ENDPOINT = '/price';

export const CACHE_TIMEOUT = 3600;
export const CACHE_KEY = 'PRICE_CONFIG';

export const PLAN_NAMES = {
  MULTI_VENUE_SAME_LOCATION_PLAN: 'MULTI_VENUE_SAME_LOCATION_PLAN', // Same Location - YES
  MULTI_VENUE_MULTI_BRANCH_PLAN: 'MULTI_VENUE_MULTI_BRANCH_PLAN', // Same Location - NO
  HOTEL_PLAN: 'HOTEL_PLAN', // HOTEL
  INDIVIDUAL_VENUE_PLAN: 'INDIVIDUAL_VENUE_PLAN', // INDIVIDUAL_VENUE
  KIDS_SPACE_SAME_LOCATION_PLAN: 'KIDS_SPACE_SAME_LOCATION_PLAN', // Kids Space Same Location - YES
  KIDS_SPACE_MULTI_BRANCH_PLAN: 'KIDS_SPACE_MULTI_BRANCH_PLAN', // // Kids Space Same Location - No
};
