export enum VenueSettings {
  INDOOR = 'INDOOR',
  OUTDOOR = 'OUTDOOR',
}

export enum VenueHire {
  PRIVATE = 'PRIVATE',
  SEMI = 'SEMI',
  SHARED = 'SHARED',
  WHOLE = 'WHOLE',
}

export enum VenueTypes {
  BALLROOM = 'BALLROOM',
  AUDI = 'AUDI',
  HALL = 'HALL',
}

export enum SpaceTypes {
  UNIQUE = 'UNIQUE',
  LUXURY = 'LUXURY',
  PREMIUM = 'PREMIUM',
}

export enum AccessibilityFeatures {
  AIRPORT = 'AIRPORT',
  BUS = 'BUS',
  SUBWAY = 'SUBWAY',
  TAXI = 'TAXI',
}

export enum VenueEntityTypes {
  VENUE = 'VENUE',
  RESTAURANT = 'RESTAURANT',
  HOTEL = 'HOTEL',
}

export enum VideoUploadTypes {
  MANUAL = 'MANUAL',
  DIRECT_LINK = 'DIRECT_LINK',
}

export enum AvailableMenu {
  KOSHER = 'KOSHER',
  VEGAN = 'VEGAN',
  GLUTTEN = 'GLUTTEN FREE',
  HALAL = 'HALAL',
}

export enum Cuisine {
  CHINESE = 'CHINESE',
  INDIAN = 'INDIAN',
  FRENCH = 'FRENCH',
}

export enum Refreshments {
  TEA = 'TEA',
  COFFEE = 'COFFEE',
  WATER = 'WATER',
}

export enum HotelViewTypes {
  CREEK = 'CREEK',
  RIVER = 'RIVER',
  LAKE = 'LAKE',
  MEADOW_FIELD = 'MEADOW_FIELD',
  DESERT = 'DESERT',
  OCEAN = 'OCEAN',
  MOUNTAIN = 'MOUNTAIN',
  FOREST = 'FOREST',
  VINEYARD = 'VINEYARD',
  VALLEY = 'VALLEY',
  CLIFFSIDE = 'CLIFFSIDE',
  ISLAND = 'ISLAND',
  SUNSET_SUNRISE = 'SUNSET_SUNRISE',
  CITYSCAPE = 'CITYSCAPE',
  SKYLINE = 'SKYLINE',
  GARDEN = 'GARDEN',
  GOLF_COURSE = 'GOLF_COURSE',
  LANDSCAPED_GROUNDS = 'LANDSCAPED_GROUNDS',
  PARK = 'PARK',
  COURTYARD = 'COURTYARD',
  COUNTRYSIDE = 'COUNTRYSIDE',
  URBAN = 'URBAN',
  GLACIER = 'GLACIER',
  TUNDRA = 'TUNDRA',
  HARBOUR = 'HARBOUR',
  WATERFALL = 'WATERFALL',
  WATERFRONT = 'WATERFRONT',
  RAVINE = 'RAVINE',
  WETLANDS = 'WETLANDS',
  MARSH = 'MARSH',
  POND = 'POND',
  CANYON = 'CANYON',
  MARINA = 'MARINA',
  BOARDWALK = 'BOARDWALK',
  PROMENADE = 'PROMENADE',
  ROOFTOP = 'ROOFTOP',
  STADIUM = 'STADIUM',
  AMUSEMENT_PARK = 'AMUSEMENT_PARK',
  PLAZA = 'PLAZA',
  HISTORICAL_DISTRICT = 'HISTORICAL_DISTRICT',
  PEDESTRIAN_STREET = 'PEDESTRIAN_STREET',
  WATERFRONT_PARK = 'WATERFRONT_PARK',
}
