export const PRICING_ENDPOINT = '/v1/pricing';
export const VENUE_ID_ENDPOINT = '/:venue_id';

export enum PricingType {
  VENUE_RENTAL = 'VENUE_RENTAL',
  MIN_SPEND_PER_PERSON = 'MIN_SPEND_PER_PERSON',
  MIN_SPEND_PRICINGS = 'MIN_SPEND_PRICINGS',
  ACCOMMODATION = 'ACCOMMODATION',
}

export enum Duration {
  PER_HOUR = 'PER_HOUR',
  PER_SESSION = 'PER_SESSION',
  PER_MORNING = 'PER_MORNING',
  PER_AFTERNOON = 'PER_AFTERNOON',
  PER_EVENING = 'PER_EVENING',
  PER_DAY = 'PER_DAY',
}

export enum Day {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}
